@startuml
set separator none
title Notify

top to bottom direction

!include <C4/C4>
!include <C4/C4_Context>
!include <C4/C4_Component>

Container_Boundary("InternalProductionSchedulingSystem.InternalProductionSchedulingSystem_boundary", "Internal Production Scheduling System", $tags="") {
  Component(InternalProductionSchedulingSystem.InternalProductionSchedulingSystem.EXScheduling, "EX Scheduling", $techn="Module", $descr="", $tags="", $link="")
  Component(InternalProductionSchedulingSystem.InternalProductionSchedulingSystem.Notify, "Notify", $techn="Module", $descr="", $tags="", $link="")
  Component(InternalProductionSchedulingSystem.InternalProductionSchedulingSystem.Common, "Common", $techn="Module", $descr="", $tags="", $link="")
  Component(InternalProductionSchedulingSystem.InternalProductionSchedulingSystem.OrderConsolidation, "Order Consolidation", $techn="Module", $descr="", $tags="", $link="")
}

Rel(InternalProductionSchedulingSystem.InternalProductionSchedulingSystem.OrderConsolidation, InternalProductionSchedulingSystem.InternalProductionSchedulingSystem.Common, "uses", $techn="", $tags="", $link="")
Rel(InternalProductionSchedulingSystem.InternalProductionSchedulingSystem.Notify, InternalProductionSchedulingSystem.InternalProductionSchedulingSystem.EXScheduling, "listens to", $techn="", $tags="", $link="")
Rel(InternalProductionSchedulingSystem.InternalProductionSchedulingSystem.Notify, InternalProductionSchedulingSystem.InternalProductionSchedulingSystem.OrderConsolidation, "listens to", $techn="", $tags="", $link="")
Rel(InternalProductionSchedulingSystem.InternalProductionSchedulingSystem.Notify, InternalProductionSchedulingSystem.InternalProductionSchedulingSystem.Common, "depends on", $techn="", $tags="", $link="")

SHOW_LEGEND(true)
@enduml